import FWCore.ParameterSet.Config as cms

demo = cms.EDAnalyzer('LostLeptonTree',
									Debug           = cms.bool    (False),
									VertexSource    = cms.InputTag('goodVertices'),
									ApplyEventWeighing = cms.untracked.int32(0),
									DoPUReweight    = cms.bool    (True),
									#PUWeigthSource  = cms.InputTag("puWeight"),
									FileNamePUDataDistribution = cms.string("RA2Classic/AdditionalInputFiles/DataPileupHistogram_RA2Summer12_190456-208686_ABCD.root"),   
									PUWeigthSource = cms.InputTag("puWeight:weight"),
									PUWeigthABSource  = cms.InputTag("puWeightAB:weight"),
									PUWeigthABCSource = cms.InputTag("puWeightABC:weight"),
									#PUWeigthRA2Source = cms.InputTag("puWeightProducer:weight"),
									PFMetSource     = cms.InputTag("patMETsPF"),
									#JetAllSource    = cms.InputTag("patJetsPF"),
									JetAllSource    = cms.InputTag("newpatJetsPFchsPt30"),
                           bTagName          = cms.string  ("combinedSecondaryVertexBJetTags"),
									genJetAllSource = cms.InputTag("ak5GenJets"),
									genParticleSource = cms.InputTag("genParticles"),
									#std. model quarks + muon+neutrinos +SUSY, quarks + gluiono,chargino,neutralino,mmuin
									genParticleList = cms.vdouble(1,2,3,4,5,6,7,8,12,13,14,16,18,1000001,1000002,1000003,1000004, 1000005, 1000006, 1000012,1000013,1000014,1000016, 2000001,2000002,2000003,2000004,2000005, 2000006,2000013,1000021,1000022,1000023,1000024, 1000025, 1000035,1000037,1000039),
									MHTSource       = cms.InputTag("mhtPFchs"),
									#MHTSource       = cms.InputTag("newPFmht"),
									HTSource        = cms.InputTag("htPFchs"),
									#HTSource        = cms.InputTag("newPFht"),
									MinPFJetPt      = cms.untracked.double(0.0),
									MinGENJetPt     = cms.untracked.double(0.0),
									HBHENoiseFiltSrc = cms.InputTag("HBHENoiseFilterRA2","HBHENoiseFilterResult","PAT"),
									MCflag          = cms.bool (False),
									no_beamHaloFilter       = cms.bool(False),
									no_eeBadScFilter        = cms.bool(False),
									no_eeNoiseFilter        = cms.bool(False),
									no_greedyMuonsFilter    = cms.bool(False),
									no_hcalLaserEventFilter = cms.bool(False),
									no_inconsistentFilter   = cms.bool(False),
									no_ra2EcalBEFilter      = cms.bool(False),
									no_ra2EcalTPFilter      = cms.bool(False),
									no_trackingFailureFilter= cms.bool(False),
									no_HBHENoiseFilter      = cms.bool(False),
									no_ecalLaserCorrFilter  = cms.bool(False),
									firedTrigNamesSource  = cms.InputTag("trigProd:firedTrigNames"),
									firedTrigsPrescalesSource  = cms.InputTag("trigProd:firedTrigPrescales")
)
